// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbyfhmXDDannEEQ2tXtJ0jeXQg6W63Ivs',
    appId: '1:704250869353:web:1f168c1bc763666aef54f8',
    messagingSenderId: '704250869353',
    projectId: 'lovescore-af368',
    authDomain: 'lovescore-af368.firebaseapp.com',
    storageBucket: 'lovescore-af368.appspot.com',
    measurementId: 'G-VCVCGSBG88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_CHReltjMWh6gQfr7-9nIchswzi9TtZI',
    appId: '1:704250869353:android:214f9e39d9c69b4cef54f8',
    messagingSenderId: '704250869353',
    projectId: 'lovescore-af368',
    storageBucket: 'lovescore-af368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3fjHivQcE39EgeulQsdEzGvY0LXYWmeo',
    appId: '1:704250869353:ios:6c480e6882a866cdef54f8',
    messagingSenderId: '704250869353',
    projectId: 'lovescore-af368',
    storageBucket: 'lovescore-af368.appspot.com',
    iosBundleId: 'com.example.liveScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3fjHivQcE39EgeulQsdEzGvY0LXYWmeo',
    appId: '1:704250869353:ios:6c480e6882a866cdef54f8',
    messagingSenderId: '704250869353',
    projectId: 'lovescore-af368',
    storageBucket: 'lovescore-af368.appspot.com',
    iosBundleId: 'com.example.liveScore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbyfhmXDDannEEQ2tXtJ0jeXQg6W63Ivs',
    appId: '1:704250869353:web:1e9d9ad62496f91eef54f8',
    messagingSenderId: '704250869353',
    projectId: 'lovescore-af368',
    authDomain: 'lovescore-af368.firebaseapp.com',
    storageBucket: 'lovescore-af368.appspot.com',
    measurementId: 'G-1MHS1G5B3F',
  );
}
